server:
  port: 9001

ribbon:
  eureka:
    enabled: true
  # 建立连接从服务器读取到可用资源时间
  ReadTimeout: 5000
  # 建立连接时间
  ConnectTimeout: 5000

spring:
  application:
    name: consumer-feign-hystrix


eureka:
  client:
    # 表示是否将自己注册进 EurekaServer 默认为 true
    register-with-eureka: true
    # 是否从 EurekaServer 抓取已有的注册信息，默认为 true，集群必须设置为 true 才能使用负载均衡
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/  # 集群版配置