server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      connect-string: 172.17.0.1:2181
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource              # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver                 # mysql 驱动
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 2580147